#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DevMind-CLI 工具模块 - 文档生成
"""

import os
from pathlib import Path
from typing import Optional, Dict, List


class DocGenerator:
    """AI文档生成器"""
    
    def __init__(self, llm_client):
        """
        初始化文档生成器
        
        Args:
            llm_client: LLM客户端
        """
        self.llm = llm_client
    
    def generate(
        self,
        module_name: Optional[str] = None,
        file_path: Optional[str] = None,
        output: Optional[str] = None,
        format: str = "markdown"
    ) -> str:
        """
        生成文档
        
        Args:
            module_name: 模块名
            file_path: 文件路径
            output: 输出文件
            format: 输出格式
            
        Returns:
            生成的文档
        """
        code = None
        source = None
        
        if file_path:
            path = Path(file_path)
            if path.exists():
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    code = f.read()
                source = f"文件: {file_path}"
        
        if module_name:
            source = f"模块: {module_name}"
            # 尝试导入模块获取docstring
            try:
                import importlib.util
                spec = importlib.util.find_spec(module_name)
                if spec and spec.origin:
                    with open(spec.origin, "r", encoding="utf-8", errors="ignore") as f:
                        code = f.read()
            except Exception:
                pass
        
        if not code:
            return "❌ 未找到代码源"
        
        lang = self._detect_language(file_path or module_name)
        
        # 生成文档
        doc = self._generate_documentation(code, lang, format)
        
        # 保存输出
        if output:
            self._save_documentation(doc, output, format)
        
        return doc
    
    def _generate_documentation(
        self,
        code: str,
        language: str,
        format: str
    ) -> str:
        """生成文档"""
        if format == "markdown":
            return self._generate_markdown(code, language)
        elif format == "html":
            return self._generate_html(code, language)
        elif format == "rst":
            return self._generate_rst(code, language)
        else:
            return self._generate_markdown(code, language)
    
    def _generate_markdown(self, code: str, language: str) -> str:
        """生成Markdown文档"""
        prompt = f"""请为以下{language}代码生成完整的Markdown格式文档，包含：
1. 模块/文件说明
2. 主要功能描述
3. 函数/类说明（包括参数、返回值）
4. 使用示例
5. 注意事项

代码:
```{language}
{code}
```"""
        
        messages = [
            {"role": "system", "content": "你是一个专业的技术文档撰写专家，请生成清晰、完整的文档。"},
            {"role": "user", "content": prompt}
        ]
        
        try:
            result = self.llm.chat(messages)
            
            doc = []
            doc.append("# 📚 DevMind-CLI 文档生成")
            doc.append("")
            doc.append("Generated documentation:")
            doc.append("")
            doc.append(result)
            doc.append("")
            doc.append("---")
            doc.append("*Generated by DevMind-CLI*")
            
            return "\n".join(doc)
        except Exception as e:
            return f"❌ 文档生成失败: {str(e)}"
    
    def _generate_html(self, code: str, language: str) -> str:
        """生成HTML文档"""
        prompt = f"""请为以下{language}代码生成HTML格式文档，包含样式和完整的API文档：

代码:
```{language}
{code}
```"""
        
        messages = [
            {"role": "system", "content": "你是一个专业的技术文档撰写专家，请生成专业的HTML文档。"},
            {"role": "user", "content": prompt}
        ]
        
        try:
            result = self.llm.chat(messages)
            
            html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API Documentation - Generated by DevMind-CLI</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; max-width: 900px; margin: 0 auto; padding: 20px; }}
        pre {{ background: #f6f8fa; padding: 16px; border-radius: 6px; overflow-x: auto; }}
        code {{ background: #f6f8fa; padding: 2px 6px; border-radius: 3px; }}
        h1 {{ border-bottom: 2px solid #e1e4e8; padding-bottom: 10px; }}
        h2 {{ margin-top: 30px; }}
    </style>
</head>
<body>
{result}
<footer style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #e1e4e8; color: #666;">
    Generated by <a href="https://github.com/gitstq/DevMind-CLI">DevMind-CLI</a>
</footer>
</body>
</html>"""
            
            return html
        except Exception as e:
            return f"❌ HTML文档生成失败: {str(e)}"
    
    def _generate_rst(self, code: str, language: str) -> str:
        """生成reStructuredText文档"""
        prompt = f"""请为以下{language}代码生成reStructuredText格式文档：

代码:
```{language}
{code}
```"""
        
        messages = [
            {"role": "system", "content": "你是一个专业的技术文档撰写专家，请生成标准的reStructuredText格式文档。"},
            {"role": "user", "content": prompt}
        ]
        
        try:
            result = self.llm.chat(messages)
            return result
        except Exception as e:
            return f"❌ RST文档生成失败: {str(e)}"
    
    def _detect_language(self, source: str) -> str:
        """检测编程语言"""
        if not source:
            return "text"
        
        if source.startswith(".") or "." in source:
            ext = Path(source).suffix.lower()
            lang_map = {
                ".py": "python",
                ".js": "javascript",
                ".ts": "typescript",
                ".go": "go",
                ".java": "java",
                ".c": "c",
                ".cpp": "cpp",
                ".rs": "rust",
            }
            return lang_map.get(ext, "text")
        
        return "python"  # 默认
    
    def _save_documentation(
        self,
        doc: str,
        output_path: str,
        format: str
    ) -> None:
        """保存文档"""
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(doc)
